# Generated by Django 3.2.4 on 2021-07-04 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_alter_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(choices=[('exactus office', 'Exactus Office'), ("owner's home", "Owner's Home"), ('in the matrix', 'In the Matrix')], default='exactus office', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'category', 'location', 'owner')},
        ),
    ]
